# Generated by Django 5.0.6 on 2024-08-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.FileField(upload_to='imagem/')),
            ],
        ),
        migrations.RenameField(
            model_name='equipe',
            old_name='Cargo',
            new_name='cargo',
        ),
        migrations.AddField(
            model_name='equipe',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipe',
            name='email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testemunho',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
